sudo: false
language: node_js
node_js:
    - stable
before_script:
    - npm install -g grunt-cli
addons:
    sauce_connect:
        username:
            secure: "FZwE9Qyolbm9RCtRdYBZiVq4NXDKcNdBX/kolZJKTH5/vKpQ8uKMnpqvhiLEeMyVOUctV39lAwj87dzISDeRZmv/ug6P6g1j3Qidvw2BN8i0WlPsRCy831YjtXbcN+ztDk4/8nTWmJjhqivtAJC65dPFRH813ROrY0CgAIUVPWU="
        access_key:
            secure: "OcQcu8YmuwDMh/1KbePTJPAsdmcK2gZOf18wajyOkfpsEVZE1EKvF3ROg697RiNkY79vxn5nQZFPkVRDD34C+sGjasvijZApbp5dMaRxO5JKfL6/m6zidTds6iYkRL3Gx8qiUu8aiTc7igGnDjXGcBC0QcZ5l06uWsGyiIGGJvs="
