sudo: false
language: node_js
node_js:
    - stable
before_script:
    - npm install -g grunt-cli
env:
    global:
        secure: "FkP/F/2n6ZEXpiMQDrOGDUxjUf+Ai+ErHSF3QjGfZjmjfxG9wRJNP6r2KyoM58jQ6HQduE94U//wYf6KTDyYduy7HurTFfF7KlaQRRJRxEebIjy/gWSXnu8pa/pffaBiD4QKX1g5PZIoocCfkbqNRI3f1PIrNgOngScv0IPWMJc="
        secure: "YB2woBM+GFCNhNPHYygFLzDoerEPLkETjzV1JpQf9WZG7fE3WyAfQYtwKz/XrjwhDhe0relt+KuCTDI+pnYy808KNv6r2ElAiVf5Q2EYl0Gf4F4knHY8rGX8OpVyS3hbvTbe1JNPwGazWP6hFYJ9tCAsTbOdw1co5JMytVtB4+I="
addons:
    sauce_connect: true
